rerun-incomplete: True
show-failed-logs: True
rerun-triggers: mtime
restart-times: 0
software-deployment-method:
  - apptainer
  - conda
printshellcmds: True
show-failed-logs: True
cores: 32
local-cores: 4
